// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOFLpweNS3QFj79RYjC-HqxrDMOfNg1DM',
    appId: '1:214929294248:web:ee32da31b9fb792152939d',
    messagingSenderId: '214929294248',
    projectId: 'campustrace-645c3',
    authDomain: 'campustrace-645c3.firebaseapp.com',
    storageBucket: 'campustrace-645c3.firebasestorage.app',
    measurementId: 'G-2FGCX1LVPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALg77qd320CJRKhVLLmoNcJMuCAuNcQAA',
    appId: '1:214929294248:android:3ad5d5530778e5b952939d',
    messagingSenderId: '214929294248',
    projectId: 'campustrace-645c3',
    storageBucket: 'campustrace-645c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ8cTPqINZmjgINnxRznd737t818emklY',
    appId: '1:214929294248:ios:2698acac0c3f4f8452939d',
    messagingSenderId: '214929294248',
    projectId: 'campustrace-645c3',
    storageBucket: 'campustrace-645c3.firebasestorage.app',
    iosBundleId: 'com.desarrolloytecnologiasantander.campustrace',
  );
}
